version: '3.6'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak

    volumes:
      - ./db:/var/lib/postgresql/data
    #  - ./serendipity-keycloak-theme/theme:/opt/jboss/keycloak/themes/serendipity

  keycloak:
    image: jboss/keycloak:12.0.4
    command:
    - "-Dkeycloak.profile.feature.upload_scripts=enabled"
    ports:
      - "8001:8080"
    depends_on:
      - postgres
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USERNAME}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    #volumes :
    #  - ./keycloak:/opt/jboss/keycloak
volumes:
  db:
